[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pygreen"
authors = [{name = "The PyGreen Team"}]
dynamic = ["version 0.1", "The Pygreen Project"]
